### ISSUE TITLE
Change "Learn More" link on calendar.

### ISSUE THREAD

**Issue by hellonycedu** [NYCEDU/nycedu-react#18]
Ideally, the "Learn More" link would go to the event's webpage and not the google calendar event information. 

For example,
<img width="1212" alt="screenshot of google chrome 11-28-16 3-46-12 pm" src="https://cloud.githubusercontent.com/assets/14281864/20685297/d8d387ac-b581-11e6-98c1-623859e188ef.png">

Currently goes to,
<img width="787" alt="screenshot of google chrome 11-28-16 3-47-14 pm" src="https://cloud.githubusercontent.com/assets/14281864/20685345/fd2d4eb2-b581-11e6-948f-c1afcd08aee6.png">

But really we want it to go to,
<img width="997" alt="screenshot of google chrome 11-28-16 3-47-52 pm" src="https://cloud.githubusercontent.com/assets/14281864/20685355/09613df6-b582-11e6-9401-a20f95271d4e.png">

Is there a way to remove the "Learn More" button so that people will just go to the URL in the event description (I can make sure a URL is included from now on)? Bonus if the URLs in the event description become clickable.

**Comment by debryc** [comment]
What's very exciting about this is that we asked people why they joined the #NYCEDU slack team and most have said that it's because they want to learn about events.

**Comment by seanperkins** [comment]
@hellonycedu To make this work, we will need to start including the link to the event page in the calendar event.

If you start including the event page link as the last line in the description we could start pulling that in and use it for the learn more.

**Comment by debryc** [comment]
I went through each event and made the last line the link! It's great to hear that it can be used for the learn more.
