### ISSUE TITLE
Remove "Jobs Page" Link

### ISSUE THREAD

**Issue by debryc** [NYCEDU/nycedu-react#34]
We've decided to remove the "Jobs Page" link because it's difficult to maintain!

<img width="394" alt="education_organization_in_nyc____nycedu" src="https://cloud.githubusercontent.com/assets/3423434/25721890/0cb5af8a-30e0-11e7-9544-42a9e152a575.png">

**Comment by seanperkins** [comment]
If it isn't included with a company then it won't show up. No need to remove it from the site, just remove it from the sheet.

**Comment by debryc** [comment]
I removed it from the sheet. Thank you!
